# Generated by Django 5.1.2 on 2024-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_auto_reply_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AutoReplySetting',
        ),
    ]
